version: 2

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests
  qa_deploy:
   jobs:
     - qa_deploy:
         filters:
           branches:
             only:
               - main
  prod_deploy:
    jobs:
      - prod_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

jobs:
  run_tests:
    docker:
      - image: cimg/ruby:2.6.5-node
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          TZ: "America/New_York"

      - image: cimg/mysql:5.7
        environment:
          TZ: "America/New_York"
          BUNDLER_VERSION: "2.2.33"
    steps:
      - checkout
      - run:
          command: |
            sudo gem update --system
            sudo apt-get install libmysqlclient-dev
            sudo gem install -f bundler --version "$BUNDLER_VERSION"
            sudo apt-get --allow-releaseinfo-change update
            sudo bundle install
            # Test that production precompile step will actually work
            sudo RAILS_ENV=production bundle exec rake assets:precompile
  qa_deploy:
    docker:
      - image: cimg/python:3.7.11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "08:05:8e:1f:ff:2e:4d:59:60:3e:a2:d5:e3:e2:b8:68"
            - "3e:58:05:d9:83:6b:a2:76:dd:12:94:fe:e4:3f:44:cb"
      - run:
          command: bash .circleci/deploy-qa.sh

  prod_deploy:
    docker:
      - image: cimg/python:3.7.11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "08:05:8e:1f:ff:2e:4d:59:60:3e:a2:d5:e3:e2:b8:68"
            - "3e:58:05:d9:83:6b:a2:76:dd:12:94:fe:e4:3f:44:cb"
      - run:
          command: bash .circleci/deploy-prod.sh
