default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  host: localhost
  database: press
  username: tupress
  password: turn1ngJ4p4n3s3
  pool: 5
  timeout: 5000

development:
 <<: *default

test:
  <<: *default
  database: press-test

production:
  <<: *default
  host: <%= ENV["TUPRESS_DB_HOST"] %>
  database: <%= ENV["TUPRESS_DB_NAME"] %>
  username: <%= ENV["TUPRESS_DB_USER"] %>
  password: <%= ENV["TUPRESS_DB_PASSWORD"] %>
